"""empty message

Revision ID: 75fa35c8c620
Revises: 14b6eccb63d5
Create Date: 2020-09-18 00:43:16.037324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75fa35c8c620'
down_revision = '14b6eccb63d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stockname', sa.String(length=64), nullable=True),
    sa.Column('trend', sa.Integer(), nullable=True),
    sa.Column('accuracy', sa.Integer(), nullable=True),
    sa.Column('risk', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_stockname'), 'stock', ['stockname'], unique=True)
    op.drop_index('ix_index_indexname', table_name='index')
    op.drop_table('index')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('indexname', sa.VARCHAR(length=64), nullable=True),
    sa.Column('daytrend', sa.VARCHAR(length=64), nullable=True),
    sa.Column('monthtrend', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_index_indexname', 'index', ['indexname'], unique=1)
    op.drop_index(op.f('ix_stock_stockname'), table_name='stock')
    op.drop_table('stock')
    # ### end Alembic commands ###
