"""empty message

Revision ID: e287b207658e
Revises: 75fa35c8c620
Create Date: 2020-09-18 01:10:28.881456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e287b207658e'
down_revision = '75fa35c8c620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stockname', sa.String(length=64), nullable=True),
    sa.Column('trend', sa.Integer(), nullable=True),
    sa.Column('accuracy', sa.Integer(), nullable=True),
    sa.Column('risk', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_stockname'), 'stock', ['stockname'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_stockname'), table_name='stock')
    op.drop_table('stock')
    # ### end Alembic commands ###
